[2021-11-22 13:13:32,488] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:13:31.092870+00:00 [queued]>
[2021-11-22 13:13:32,504] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:13:31.092870+00:00 [queued]>
[2021-11-22 13:13:32,505] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:13:32,506] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-22 13:13:32,507] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:13:32,524] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): Extract> on 2021-11-22 13:13:31.092870+00:00
[2021-11-22 13:13:32,530] {standard_task_runner.py:52} INFO - Started process 447 to run task
[2021-11-22 13:13:32,534] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ELT-python-snowflake', 'Extract', 'manual__2021-11-22T13:13:31.092870+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/ELT-python-snowflake.py', '--cfg-path', '/tmp/tmp3x708o3m', '--error-file', '/tmp/tmpfvt8arjh']
[2021-11-22 13:13:32,535] {standard_task_runner.py:77} INFO - Job 59: Subtask Extract
[2021-11-22 13:13:32,595] {logging_mixin.py:109} INFO - Running <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:13:31.092870+00:00 [running]> on host bd3f5d3b0fb3
[2021-11-22 13:13:32,657] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT-python-snowflake
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2021-11-22T13:13:31.092870+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-22T13:13:31.092870+00:00
[2021-11-22 13:13:32,658] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-22 13:13:32,660] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/elt/user-orders/extract-load/mysql_to_s3.py']
[2021-11-22 13:13:32,682] {subprocess.py:85} INFO - Output:
[2021-11-22 13:13:38,760] {subprocess.py:89} INFO - WARNING: An illegal reflective access operation has occurred
[2021-11-22 13:13:38,762] {subprocess.py:89} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-11-22 13:13:38,763] {subprocess.py:89} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-11-22 13:13:38,764] {subprocess.py:89} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-11-22 13:13:38,765] {subprocess.py:89} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-11-22 13:13:39,781] {subprocess.py:89} INFO - 21/11/22 13:13:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-11-22 13:13:40,396] {subprocess.py:89} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-11-22 13:13:40,399] {subprocess.py:89} INFO - Setting default log level to "WARN".
[2021-11-22 13:13:40,401] {subprocess.py:89} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2021-11-22 13:13:47,677] {subprocess.py:89} INFO - Mon Nov 22 13:13:47 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:13:48,764] {subprocess.py:89} INFO - Mon Nov 22 13:13:48 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:13:48,766] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,767] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:13:48,768] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,770] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,772] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,774] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:13:48,775] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,776] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:13:48,777] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:48,778] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,779] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:13:48,783] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,785] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:48,789] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:13:48,790] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:13:48,793] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:13:48,795] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:13:48,796] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:13:48,798] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:13:48,799] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:71)
[2021-11-22 13:13:48,805] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
[2021-11-22 13:13:48,806] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
[2021-11-22 13:13:48,808] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:354)
[2021-11-22 13:13:48,810] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
[2021-11-22 13:13:48,811] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
[2021-11-22 13:13:48,812] {subprocess.py:89} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2021-11-22 13:13:48,813] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
[2021-11-22 13:13:48,814] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
[2021-11-22 13:13:48,815] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-22 13:13:48,816] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-22 13:13:48,818] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-22 13:13:48,818] {subprocess.py:89} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-22 13:13:48,820] {subprocess.py:89} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2021-11-22 13:13:48,820] {subprocess.py:89} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-11-22 13:13:48,821] {subprocess.py:89} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2021-11-22 13:13:48,822] {subprocess.py:89} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2021-11-22 13:13:48,823] {subprocess.py:89} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2021-11-22 13:13:48,825] {subprocess.py:89} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2021-11-22 13:13:48,826] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:13:48,827] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,828] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,829] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:13:48,830] {subprocess.py:89} INFO - 
[2021-11-22 13:13:48,831] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,556] {subprocess.py:89} INFO - Mon Nov 22 13:13:57 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:13:57,794] {subprocess.py:89} INFO - [Stage 0:>                                                          (0 + 1) / 1]Mon Nov 22 13:13:57 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:13:57,796] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,797] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:13:57,798] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,799] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,800] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,801] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:13:57,802] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,802] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:13:57,804] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:57,805] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,805] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:13:57,806] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,807] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:57,808] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:13:57,809] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:13:57,809] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:13:57,810] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:13:57,811] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:13:57,812] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:13:57,813] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:13:57,814] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:13:57,815] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:13:57,816] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:13:57,817] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:13:57,818] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:13:57,819] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:13:57,820] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2021-11-22 13:13:57,821] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2021-11-22 13:13:57,822] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2021-11-22 13:13:57,823] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2021-11-22 13:13:57,825] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2021-11-22 13:13:57,826] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2021-11-22 13:13:57,827] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2021-11-22 13:13:57,828] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:13:57,829] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:13:57,830] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:13:57,831] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:13:57,832] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:13:57,833] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:13:57,834] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:13:57,835] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,836] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,837] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:13:57,838] {subprocess.py:89} INFO - 
[2021-11-22 13:13:57,839] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,038] {subprocess.py:89} INFO -                                                                                 Mon Nov 22 13:13:59 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:13:59,090] {subprocess.py:89} INFO - Mon Nov 22 13:13:59 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:13:59,091] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,092] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:13:59,093] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,094] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,095] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,096] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:13:59,097] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,098] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:13:59,098] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:59,099] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,100] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:13:59,101] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,102] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:59,104] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:13:59,105] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:13:59,106] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:13:59,107] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:13:59,109] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:13:59,110] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:13:59,110] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:13:59,111] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:13:59,113] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:13:59,114] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:13:59,115] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
[2021-11-22 13:13:59,116] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:13:59,117] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:13:59,117] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:13:59,118] {subprocess.py:89} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
[2021-11-22 13:13:59,119] {subprocess.py:89} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
[2021-11-22 13:13:59,120] {subprocess.py:89} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2021-11-22 13:13:59,121] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2021-11-22 13:13:59,122] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2021-11-22 13:13:59,123] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:13:59,125] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:13:59,126] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:13:59,127] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:13:59,128] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:13:59,130] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:13:59,131] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:13:59,132] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,132] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,134] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:13:59,135] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,138] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,395] {subprocess.py:89} INFO - Mon Nov 22 13:13:59 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:13:59,429] {subprocess.py:89} INFO - Mon Nov 22 13:13:59 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:13:59,431] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,432] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:13:59,438] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,442] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,443] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,444] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:13:59,446] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,448] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:13:59,449] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:59,453] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,455] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:13:59,461] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,465] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:13:59,466] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:13:59,467] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:13:59,468] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:13:59,471] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:13:59,473] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:13:59,475] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:13:59,476] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:13:59,479] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:13:59,480] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:13:59,485] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:13:59,490] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:13:59,491] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:13:59,493] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:13:59,494] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2021-11-22 13:13:59,496] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2021-11-22 13:13:59,498] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2021-11-22 13:13:59,502] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2021-11-22 13:13:59,503] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2021-11-22 13:13:59,504] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2021-11-22 13:13:59,505] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2021-11-22 13:13:59,506] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:13:59,507] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:13:59,508] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:13:59,508] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:13:59,510] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:13:59,511] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:13:59,512] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:13:59,513] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,514] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,515] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:13:59,516] {subprocess.py:89} INFO - 
[2021-11-22 13:13:59,517] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,631] {subprocess.py:89} INFO - Mon Nov 22 13:14:00 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:14:00,662] {subprocess.py:89} INFO - Mon Nov 22 13:14:00 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:14:00,664] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,665] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:14:00,666] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,667] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,667] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,669] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:14:00,670] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,672] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:14:00,673] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:00,675] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,676] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:14:00,677] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,678] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:00,679] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:14:00,681] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:14:00,682] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:14:00,684] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:14:00,685] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:14:00,686] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:14:00,687] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:71)
[2021-11-22 13:14:00,688] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
[2021-11-22 13:14:00,689] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
[2021-11-22 13:14:00,690] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:354)
[2021-11-22 13:14:00,691] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
[2021-11-22 13:14:00,693] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
[2021-11-22 13:14:00,694] {subprocess.py:89} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2021-11-22 13:14:00,695] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
[2021-11-22 13:14:00,697] {subprocess.py:89} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
[2021-11-22 13:14:00,698] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-22 13:14:00,699] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-22 13:14:00,701] {subprocess.py:89} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-22 13:14:00,702] {subprocess.py:89} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-22 13:14:00,703] {subprocess.py:89} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2021-11-22 13:14:00,704] {subprocess.py:89} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-11-22 13:14:00,705] {subprocess.py:89} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2021-11-22 13:14:00,706] {subprocess.py:89} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2021-11-22 13:14:00,708] {subprocess.py:89} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2021-11-22 13:14:00,710] {subprocess.py:89} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2021-11-22 13:14:00,711] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:14:00,712] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,713] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,714] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:14:00,715] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,716] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,832] {subprocess.py:89} INFO - Mon Nov 22 13:14:00 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:14:00,866] {subprocess.py:89} INFO - Mon Nov 22 13:14:00 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:14:00,867] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,869] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:14:00,870] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,872] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,873] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,874] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:14:00,874] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,876] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:14:00,877] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:00,878] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,879] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:14:00,882] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,883] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:00,884] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:14:00,885] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:14:00,886] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:14:00,887] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:14:00,888] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:14:00,889] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:14:00,891] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:14:00,892] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:14:00,893] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:14:00,894] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:14:00,901] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:14:00,902] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:14:00,904] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:14:00,905] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2021-11-22 13:14:00,906] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2021-11-22 13:14:00,907] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2021-11-22 13:14:00,909] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2021-11-22 13:14:00,910] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2021-11-22 13:14:00,911] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2021-11-22 13:14:00,912] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2021-11-22 13:14:00,913] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:14:00,915] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:14:00,916] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:14:00,917] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:14:00,918] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:14:00,920] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:14:00,921] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:14:00,922] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,923] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,924] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:14:00,925] {subprocess.py:89} INFO - 
[2021-11-22 13:14:00,926] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,187] {subprocess.py:89} INFO - Mon Nov 22 13:14:01 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:14:01,223] {subprocess.py:89} INFO - Mon Nov 22 13:14:01 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:14:01,225] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,226] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:14:01,227] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,228] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,230] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,231] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:14:01,232] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,233] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:14:01,234] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:01,235] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,236] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:14:01,237] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,238] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:01,239] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:14:01,240] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:14:01,247] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:14:01,249] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:14:01,252] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:14:01,255] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:14:01,258] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:14:01,262] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:14:01,265] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:14:01,267] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:14:01,268] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
[2021-11-22 13:14:01,269] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:14:01,270] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:14:01,272] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:14:01,288] {subprocess.py:89} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
[2021-11-22 13:14:01,290] {subprocess.py:89} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
[2021-11-22 13:14:01,291] {subprocess.py:89} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2021-11-22 13:14:01,294] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2021-11-22 13:14:01,296] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2021-11-22 13:14:01,298] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:14:01,300] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:14:01,301] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:14:01,302] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:14:01,303] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:14:01,304] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:14:01,306] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:14:01,308] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,309] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,311] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:14:01,313] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,314] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,520] {subprocess.py:89} INFO - Mon Nov 22 13:14:01 UTC 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[2021-11-22 13:14:01,562] {subprocess.py:89} INFO - Mon Nov 22 13:14:01 UTC 2021 WARN: Caught while disconnecting...
[2021-11-22 13:14:01,563] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,565] {subprocess.py:89} INFO - EXCEPTION STACK TRACE:
[2021-11-22 13:14:01,567] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,569] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,570] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,571] {subprocess.py:89} INFO - ** BEGIN NESTED EXCEPTION **
[2021-11-22 13:14:01,572] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,575] {subprocess.py:89} INFO - javax.net.ssl.SSLException
[2021-11-22 13:14:01,577] {subprocess.py:89} INFO - MESSAGE: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:01,580] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,581] {subprocess.py:89} INFO - STACKTRACE:
[2021-11-22 13:14:01,582] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,584] {subprocess.py:89} INFO - javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[2021-11-22 13:14:01,586] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:763)
[2021-11-22 13:14:01,587] {subprocess.py:89} INFO - 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:742)
[2021-11-22 13:14:01,588] {subprocess.py:89} INFO - 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
[2021-11-22 13:14:01,589] {subprocess.py:89} INFO - 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
[2021-11-22 13:14:01,590] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
[2021-11-22 13:14:01,591] {subprocess.py:89} INFO - 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
[2021-11-22 13:14:01,592] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.close$1(JDBCRDD.scala:259)
[2021-11-22 13:14:01,593] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.$anonfun$compute$8(JDBCRDD.scala:308)
[2021-11-22 13:14:01,594] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
[2021-11-22 13:14:01,597] {subprocess.py:89} INFO - 	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:36)
[2021-11-22 13:14:01,600] {subprocess.py:89} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2021-11-22 13:14:01,603] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2021-11-22 13:14:01,607] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2021-11-22 13:14:01,622] {subprocess.py:89} INFO - 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2021-11-22 13:14:01,629] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2021-11-22 13:14:01,632] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2021-11-22 13:14:01,634] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2021-11-22 13:14:01,636] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2021-11-22 13:14:01,638] {subprocess.py:89} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2021-11-22 13:14:01,639] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2021-11-22 13:14:01,640] {subprocess.py:89} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2021-11-22 13:14:01,642] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2021-11-22 13:14:01,647] {subprocess.py:89} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2021-11-22 13:14:01,655] {subprocess.py:89} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2021-11-22 13:14:01,656] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-22 13:14:01,657] {subprocess.py:89} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-22 13:14:01,663] {subprocess.py:89} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-22 13:14:01,664] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,669] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,682] {subprocess.py:89} INFO - ** END NESTED EXCEPTION **
[2021-11-22 13:14:01,684] {subprocess.py:89} INFO - 
[2021-11-22 13:14:01,688] {subprocess.py:89} INFO - 
[2021-11-22 13:14:02,118] {subprocess.py:89} INFO - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-11-22 13:14:02,119] {subprocess.py:89} INFO -   _expected_pyarrow_version,
[2021-11-22 13:14:02,120] {subprocess.py:89} INFO - uploading entity: USERS
[2021-11-22 13:14:02,121] {subprocess.py:89} INFO - new:
[2021-11-22 13:14:02,122] {subprocess.py:89} INFO - +---+-------+---+--------------------+-------------------+----------+
[2021-11-22 13:14:02,123] {subprocess.py:89} INFO - | id|   name|age|             address|         created_at|updated_at|
[2021-11-22 13:14:02,123] {subprocess.py:89} INFO - +---+-------+---+--------------------+-------------------+----------+
[2021-11-22 13:14:02,124] {subprocess.py:89} INFO - |  1|michael| 23| London st square 28|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,125] {subprocess.py:89} INFO - |  2|   john| 44|Madrid ST blabla 232|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,125] {subprocess.py:89} INFO - |  3|   raul| 65|        Tokyo 2NW343|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,126] {subprocess.py:89} INFO - +---+-------+---+--------------------+-------------------+----------+
[2021-11-22 13:14:02,126] {subprocess.py:89} INFO - 
[2021-11-22 13:14:02,127] {subprocess.py:89} INFO - uploading to s3:
[2021-11-22 13:14:02,128] {subprocess.py:89} INFO - uploading entity: ORDERS
[2021-11-22 13:14:02,129] {subprocess.py:89} INFO - new:
[2021-11-22 13:14:02,129] {subprocess.py:89} INFO - +---+-------+-----+----------+-------------------+----------+
[2021-11-22 13:14:02,130] {subprocess.py:89} INFO - | id|id_user|spent|    status|         created_at|updated_at|
[2021-11-22 13:14:02,130] {subprocess.py:89} INFO - +---+-------+-----+----------+-------------------+----------+
[2021-11-22 13:14:02,131] {subprocess.py:89} INFO - |  1|      1|   34|processing|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,132] {subprocess.py:89} INFO - |  2|      2| 2300|processing|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,133] {subprocess.py:89} INFO - |  3|      3| 1100|processing|2021-11-22 13:06:45|      null|
[2021-11-22 13:14:02,134] {subprocess.py:89} INFO - +---+-------+-----+----------+-------------------+----------+
[2021-11-22 13:14:02,135] {subprocess.py:89} INFO - 
[2021-11-22 13:14:02,136] {subprocess.py:89} INFO - uploading to s3:
[2021-11-22 13:14:02,994] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-22 13:14:03,022] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=ELT-python-snowflake, task_id=Extract, execution_date=20211122T131331, start_date=20211122T131332, end_date=20211122T131403
[2021-11-22 13:14:03,065] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-22 13:14:03,113] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
