[2021-11-22 13:31:23,531] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:31:22.135157+00:00 [queued]>
[2021-11-22 13:31:23,547] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:31:22.135157+00:00 [queued]>
[2021-11-22 13:31:23,548] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:31:23,549] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-22 13:31:23,550] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:31:23,568] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): Extract> on 2021-11-22 13:31:22.135157+00:00
[2021-11-22 13:31:23,574] {standard_task_runner.py:52} INFO - Started process 3996 to run task
[2021-11-22 13:31:23,579] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ELT-python-snowflake', 'Extract', 'manual__2021-11-22T13:31:22.135157+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/ELT-python-snowflake.py', '--cfg-path', '/tmp/tmpmmyymbag', '--error-file', '/tmp/tmpj5q4z9oj']
[2021-11-22 13:31:23,580] {standard_task_runner.py:77} INFO - Job 79: Subtask Extract
[2021-11-22 13:31:23,643] {logging_mixin.py:109} INFO - Running <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:31:22.135157+00:00 [running]> on host bd3f5d3b0fb3
[2021-11-22 13:31:23,714] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT-python-snowflake
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2021-11-22T13:31:22.135157+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-22T13:31:22.135157+00:00
[2021-11-22 13:31:23,716] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-22 13:31:23,717] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/elt/user-orders/extract-load/mysql_to_s3.py']
[2021-11-22 13:31:23,733] {subprocess.py:85} INFO - Output:
[2021-11-22 13:31:28,959] {subprocess.py:89} INFO - WARNING: An illegal reflective access operation has occurred
[2021-11-22 13:31:28,974] {subprocess.py:89} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-11-22 13:31:28,976] {subprocess.py:89} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-11-22 13:31:28,980] {subprocess.py:89} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-11-22 13:31:28,984] {subprocess.py:89} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-11-22 13:31:29,904] {subprocess.py:89} INFO - 21/11/22 13:31:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-11-22 13:31:30,502] {subprocess.py:89} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-11-22 13:31:30,503] {subprocess.py:89} INFO - Setting default log level to "WARN".
[2021-11-22 13:31:30,505] {subprocess.py:89} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2021-11-22 13:31:47,691] {subprocess.py:89} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-11-22 13:31:47,693] {subprocess.py:89} INFO -   _expected_pyarrow_version,
[2021-11-22 13:31:47,694] {subprocess.py:89} INFO - uploading entity: USERS
[2021-11-22 13:31:47,697] {subprocess.py:89} INFO - select * from users where created_at > '2021-11-22 13:17:15' or updated_at > '2021-11-22 13:17:15'
[2021-11-22 13:31:47,698] {subprocess.py:89} INFO - new:
[2021-11-22 13:31:47,700] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:31:47,701] {subprocess.py:89} INFO - | id|name|age|address|created_at|updated_at|
[2021-11-22 13:31:47,702] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:31:47,703] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:31:47,704] {subprocess.py:89} INFO - 
[2021-11-22 13:31:47,706] {subprocess.py:89} INFO - uploading entity: ORDERS
[2021-11-22 13:31:47,707] {subprocess.py:89} INFO - select * from orders where created_at > '2021-11-22 13:17:15' or updated_at > '2021-11-22 13:17:15'
[2021-11-22 13:31:47,708] {subprocess.py:89} INFO - new:
[2021-11-22 13:31:47,709] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:31:47,711] {subprocess.py:89} INFO - | id|id_user|spent|status|created_at|updated_at|
[2021-11-22 13:31:47,711] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:31:47,713] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:31:47,714] {subprocess.py:89} INFO - 
[2021-11-22 13:31:48,622] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-22 13:31:48,669] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=ELT-python-snowflake, task_id=Extract, execution_date=20211122T133122, start_date=20211122T133123, end_date=20211122T133148
[2021-11-22 13:31:48,717] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-22 13:31:48,773] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
